# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Huec < Formula
  desc "A powerful CLI for controlling Philips Hue lights."
  homepage "https://github.com/firstthumb/huec"
  version "1.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.6/huec_1.0.6_macOS_x86_64.tar.gz"
      sha256 "317296cdb927cc9be4c01dcf33ba95c065426e4feb2d7efa422c8fb862908426"
    end
    if Hardware::CPU.arm?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.6/huec_1.0.6_macOS_arm64.tar.gz"
      sha256 "e1feedcb266954e9e08f6b5735e0c39fbc804d1e4c07cf9c7b80b95233cd3252"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.6/huec_1.0.6_Linux_x86_64.tar.gz"
      sha256 "e6957257507d7527a534898ef850d86a51a157596ba2e21cd74b208778486c48"
    end
  end

  def install
    bin.install "huec"
  end

  def caveats; <<~EOS
    Control Philips Hue lights
  EOS
  end
end
