# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Huec < Formula
  desc "A powerful CLI for controlling Philips Hue lights."
  homepage "https://github.com/firstthumb/huec"
  version "1.0.20"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.20/huec_1.0.20_macOS_x86_64.tar.gz"
      sha256 "2e7ef18233584edb88d68d99cfc5fe1001a0b8668ac712715b9383659a028170"
    end
    if Hardware::CPU.arm?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.20/huec_1.0.20_macOS_arm64.tar.gz"
      sha256 "19b7ff63e1b102450ef63afdc9cca501a9f0016ad0e44808fa58a8502f8ec523"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/firstthumb/huec/releases/download/v1.0.20/huec_1.0.20_Linux_x86_64.tar.gz"
      sha256 "dc72fb2a370acd4448f986adc4c13284ed0696113dcd682892c7bed2de3f968c"
    end
  end

  def install
    bin.install "huec"
  end

  def caveats; <<~EOS
    Control Philips Hue lights
  EOS
  end
end
